server:
  # 端口
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /wechat/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.218.220:3306/wechat_mmtls?useUnicode=true&useSSL=false&characterEncoding=utf8&&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 3000
      connection-test-query: SELECT 1
  rocketmq:
    name-server-address: 180.76.163.53:9876
    producer-group: producer-wechat
    proxy-topic: wechat-delay
    consumer-topic: wechat
    consumer-group: wechat
    tags:
      qunGroup: scanIntoUrlGroupTag
      groupChat: groupChatTag
  redis:
    password: iseeyou_123
    host: 120.77.218.220
    database: 7
    timeout: 5000ms
  cache:
    type: redis   # 指定使用的缓存类型
  cache-names: contacts
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxx.server.pojo
  configuration:
    map-underscore-to-camel-case: false

wechat:
  rootUrl: http://27.151.13.31:18080
  file:
    basePath: /home/xieyi/xieyi/image

logging:
  level:
    com.xxx.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  #JWT加解密使用的密钥
  secret: wechat-secret
  #JWT的超期限时间 (60*60*24)
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: Bearer