server:
  # 端口
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.218.220:3306/wechat?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 3000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxx.server.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.xxx.server.mapper: debug